### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by dingelish** [scrtlabs/enigma-core-deprecated#4]
Greetings!

Author of [rust-sgx-sdk](https://github.com/baidu/rust-sgx-sdk) here. Good to see that you guys are doing fantastic jobs using our SDK and hope you guys are doing well!

Of course you guys are free to use the SDK and do whatever you want. Would you please add something regards to the License we use? and some acknowledgement in your Readme would be pretty much awesome! 

Of course, if you guys have recommendations or any ideas about this SDK, please feel free to contact me at [rustsgx@gmail.com](mailto:rustsgx@gmail.com). Thanks!

Best,
Yu

**Comment by lacabra** [comment]
Hi Yu!

Thanks for your very friendly note about licensing. I have added BSD license to this repo (cb9ce51f803064e4bf3b6cf39af41a06180801a5), and copied over the license from your repo that details the corresponding licenses from all the subcomponents.

I have also added an acknowledgements section with a mention to your project (3f280df87b524d4ab1c1cf98fa6ef5112c5196f3). Again, thanks for pointing this out.

I'm closing this issue as resolved, but please let me know if you have any outstanding concerns, or you would like to suggest any additional edits. 

Thank you,
Victor

**Comment by dingelish** [comment]
Thank you so much! Really appreciate your help!

**Comment by elichai** [comment]
This issue was moved to enigmampc/enigma-core-internal#3
